### ISSUE TITLE
Add CLI handling

### ISSUE THREAD

**Issue by chulderman** [obscurehero/stellar-avarice#1]
**Options:**
- HTTP vs Torrent download
- Create torrent
- Check for new release
- Print info (latest release, up-to-date?)
- more?

**Comment by tcarrio** [comment]
You want these as flags on the command? 

For example:

<ul>
<li>--download={http,torrent}, -d {http,torrent}</li>
<li>--create {params}, -c {params}</li>
<li>--sync, -S</li>
<li>--print, -p</li>
</ul>

**Comment by tcarrio** [comment]
Libraries for CLI application building
http://pythonhosted.org/pyCLI/
https://docs.python.org/3.5/library/argparse.html

**Comment by tcarrio** [comment]
Argparse seems like a good library to use, since it's included in Python 2.7 and 3.X

**Comment by chulderman** [comment]
> Argparse seems like a good library to use, since it's included in Python 2.7 and 3.X

Opened up a new branch [argparse_implementation](https://github.com/obscurehero/stellar-avarice/tree/argparse_implementation)

**Comment by chulderman** [comment]
Closed - 703286e16df1a018483fdfea281023f3f6b441bf
